//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class statistics {
    
    private string readyMeaningsQuantityField;
    
    private string activeMeaningsQuantityField;
    
    private string learnedMeaningsQuantityField;
    
    private string statusField;
    
    private string answeredField;
    
    private string shownField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string readyMeaningsQuantity {
        get {
            return this.readyMeaningsQuantityField;
        }
        set {
            this.readyMeaningsQuantityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string activeMeaningsQuantity {
        get {
            return this.activeMeaningsQuantityField;
        }
        set {
            this.activeMeaningsQuantityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string learnedMeaningsQuantity {
        get {
            return this.learnedMeaningsQuantityField;
        }
        set {
            this.learnedMeaningsQuantityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string answered {
        get {
            return this.answeredField;
        }
        set {
            this.answeredField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string shown {
        get {
            return this.shownField;
        }
        set {
            this.shownField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class dictionary {
    
    private statistics[] statisticsField;
    
    private dictionaryCard[] cardField;
    
    private string formatVersionField;
    
    private string titleField;
    
    private string sourceLanguageIdField;
    
    private string destinationLanguageIdField;
    
    private string nextWordIdField;
    
    private string targetNamespaceField;
    
    private string soundfileField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("statistics")]
    public statistics[] statistics {
        get {
            return this.statisticsField;
        }
        set {
            this.statisticsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("card", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public dictionaryCard[] card {
        get {
            return this.cardField;
        }
        set {
            this.cardField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string formatVersion {
        get {
            return this.formatVersionField;
        }
        set {
            this.formatVersionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string sourceLanguageId {
        get {
            return this.sourceLanguageIdField;
        }
        set {
            this.sourceLanguageIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string destinationLanguageId {
        get {
            return this.destinationLanguageIdField;
        }
        set {
            this.destinationLanguageIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nextWordId {
        get {
            return this.nextWordIdField;
        }
        set {
            this.nextWordIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string targetNamespace {
        get {
            return this.targetNamespaceField;
        }
        set {
            this.targetNamespaceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string soundfile {
        get {
            return this.soundfileField;
        }
        set {
            this.soundfileField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class dictionaryCard {
    
    private string wordField;
    
    private dictionaryCardMeaningsMeaning[][] meaningsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string word {
        get {
            return this.wordField;
        }
        set {
            this.wordField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("meaning", typeof(dictionaryCardMeaningsMeaning), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public dictionaryCardMeaningsMeaning[][] meanings {
        get {
            return this.meaningsField;
        }
        set {
            this.meaningsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class dictionaryCardMeaningsMeaning {
    
    private statistics[] statisticsField;
    
    private dictionaryCardMeaningsMeaningTranslationsWord[][] translationsField;
    
    private dictionaryCardMeaningsMeaningExamples[] examplesField;
    
    private dictionaryCardMeaningsMeaningSound[] soundField;
    
    private string transcriptionField;
    
    private string soundfileField;
    
    private string partOfSpeechField;
    
    private string meaningIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("statistics")]
    public statistics[] statistics {
        get {
            return this.statisticsField;
        }
        set {
            this.statisticsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("word", typeof(dictionaryCardMeaningsMeaningTranslationsWord), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public dictionaryCardMeaningsMeaningTranslationsWord[][] translations {
        get {
            return this.translationsField;
        }
        set {
            this.translationsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("examples", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public dictionaryCardMeaningsMeaningExamples[] examples {
        get {
            return this.examplesField;
        }
        set {
            this.examplesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("sound", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public dictionaryCardMeaningsMeaningSound[] sound {
        get {
            return this.soundField;
        }
        set {
            this.soundField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string transcription {
        get {
            return this.transcriptionField;
        }
        set {
            this.transcriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string soundfile {
        get {
            return this.soundfileField;
        }
        set {
            this.soundfileField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string partOfSpeech {
        get {
            return this.partOfSpeechField;
        }
        set {
            this.partOfSpeechField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string meaningId {
        get {
            return this.meaningIdField;
        }
        set {
            this.meaningIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class dictionaryCardMeaningsMeaningTranslationsWord {
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class dictionaryCardMeaningsMeaningExamples {
    
    private string exampleField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string example {
        get {
            return this.exampleField;
        }
        set {
            this.exampleField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class dictionaryCardMeaningsMeaningSound {
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class NewDataSet {
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("dictionary", typeof(dictionary))]
    //[System.Xml.Serialization.XmlElementAttribute("statistics", typeof(statistics))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}
